# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'ChatChat' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


pod 'Firebase', '>= 2.5.0'
pod 'JSQMessagesViewController'


  # Pods for ChatChat

end
